# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playthru < Formula
  desc "playthru CLI"
  homepage "https://github.com/thommorais/playthru"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/thommorais/homebrew-playthru/releases/download/v0.1.0/playthru_0.1.0_darwin.tar.gz"
  sha256 "74d72cac6e644836b00038b60bfc1d270e983523baecf070b7762df2053f573c"

  define_method(:install) do
    bin.install "playthru"
  end

  test do
    system "#{bin}/playthru", "--version"
  end
end
