# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playthru < Formula
  desc "playthru CLI"
  homepage "https://github.com/thommorais/playthru"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/thommorais/playthru-releases/releases/download/v0.1.0/playthru_0.1.0_darwin.tar.gz", using: CurlDownloadStrategy
  sha256 "cf05d1b051e30b90b6dfa12c9e22d5e5df5546ecc68c21dee77345158ba672ea"

  define_method(:install) do
    bin.install "playthru"
  end

  test do
    system "#{bin}/playthru", "--version"
  end
end
