# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playthru < Formula
  desc "playthru CLI"
  homepage "https://github.com/thommorais/playthru"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/thommorais/playthru/releases/download/v0.1.0/playthru_0.1.0_darwin.tar.gz"
  sha256 "6ae70504cdfe4f8169d01ffb910795020185524a7ef0cf55f3018ebbd2e25369"

  define_method(:install) do
    bin.install "playthru"
  end

  test do
    system "#{bin}/playthru", "--version"
  end
end
